/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.9
 * Generated at: 2025-08-05 18:17:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.SubViews;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class IntroductionColumn_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!-- <!DOCTYPE html> -->\n");
      out.write("<!-- <html> -->\n");
      out.write("\n");
      out.write("<!-- <head> -->\n");
      out.write("<!--   <meta charset=\"UTF-8\" /> -->\n");
      out.write("<!--   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1\"> -->\n");
      out.write("<!--   <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script> -->\n");
      out.write("<!--   <script src=\"https://kit.fontawesome.com/14c95c3413.js\" crossorigin=\"anonymous\"></script> -->\n");
      out.write("\n");
      out.write("<!-- </head> -->\n");
      out.write("\n");
      out.write("<!-- <body> -->\n");
      out.write("  <footer class=\"aboutallbag\">\n");
      out.write("    <div class=\"aboutbag\">\n");
      out.write("      <div id=\"ABUS\">\n");
      out.write("        關於\n");
      out.write("        <address>地址:XXXXXXXXXX</address>\n");
      out.write("        電話:(xx)xxxx-xxxx\n");
      out.write("      </div>\n");
      out.write("      <div class=\"SocialNetworking\">\n");
      out.write("        <div class=\"SNbag\">\n");
      out.write("          <a href=\"https://line.me/zh-hant/\" id=\"line\"><i class=\"fab fa-line\"></i></a>\n");
      out.write("          <a href=\"https://line.me/zh-hant/\" class=\"SNtext\">LINE</a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"SNbag\">\n");
      out.write("          <a href=\"https://twitter.com/?lang=zh-Hant\" id=\"twitter\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("          <a href=\"https://twitter.com/?lang=zh-Hant\" class=\"SNtext\">TWITTER</a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"SNbag\">\n");
      out.write("          <a href=\"https://zh-tw.facebook.com/\" id=\"facebook\"><i class=\"fa fa-facebook-square\"></i></a>\n");
      out.write("          <a href=\"https://zh-tw.facebook.com/\" class=\"SNtext\">FACEBOOK</a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </footer>\n");
      out.write("  <style>\n");
      out.write("    body {\n");
      out.write("      margin: 0;\n");
      out.write("      border: 0;\n");
      out.write("      padding: 0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .aboutallbag {\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("      width: 100%;\n");
      out.write("      height: 17em;\n");
      out.write("      background: linear-gradient(90deg, #798c99 40%, #26262c 70%);\n");
      out.write("\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .aboutbag {\n");
      out.write("      display: grid;\n");
      out.write("      grid-template-columns: 15em 1fr;\n");
      out.write("      grid-gap: 2em;\n");
      out.write("      width: 100%;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #ABUS {\n");
      out.write("      display: flex;\n");
      out.write("      flex-direction: column;\n");
      out.write("      font-size: 2em;\n");
      out.write("      white-space: nowrap;\n");
      out.write("      padding-left:0.5em;\n");
      out.write("      justify-content: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .SocialNetworking {\n");
      out.write("      display: flex;\n");
      out.write("      justify-content: center;\n");
      out.write("      align-items: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .SocialNetworking>a {\n");
      out.write("      display: flex;\n");
      out.write("      text-decoration: none;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .SNbag {\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .SNtext {\n");
      out.write("      font-size: 2em;\n");
      out.write("      padding: 1em 0;\n");
      out.write("      display: none;\n");
      out.write("      color: rgb(255, 220, 103);\n");
      out.write("      animation: AboutAnimate 3s linear infinite;\n");
      out.write("      text-shadow:\n");
      out.write("        0 0 50px #0072ff,\n");
      out.write("        0 0 75px #0072ff,\n");
      out.write("        0 0 100px #0072ff,\n");
      out.write("        0 0 125px #0072ff;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .SNtext:hover {\n");
      out.write("      color: #fff;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .SNbag:hover .SNtext {\n");
      out.write("      display: block;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #line,\n");
      out.write("    #twitter,\n");
      out.write("    #facebook {\n");
      out.write("      font-size: 5em;\n");
      out.write("      background-color: #18191f;\n");
      out.write("      color: #fff;\n");
      out.write("      box-shadow:\n");
      out.write("        2px 2px 2px #00000080,\n");
      out.write("        5px 1px 6px #00000080,\n");
      out.write("        2px 2px 5px #00000080,\n");
      out.write("        2px 2px 3px #00000080,\n");
      out.write("        inset 2px 2px 10px #00000080,\n");
      out.write("        inset 2px 2px 10px #00000080,\n");
      out.write("        inset 2px 2px 10px #00000080,\n");
      out.write("        inset 2px 2px 10px #00000080;\n");
      out.write("      border-radius: 0.4em;\n");
      out.write("      padding: 11px 19px;\n");
      out.write("      margin: 0 0.2em;\n");
      out.write("      animation: AboutAnimate 3s linear infinite;\n");
      out.write("      text-shadow:\n");
      out.write("        0 0 25px #0072ff,\n");
      out.write("        0 0 50px #0072ff,\n");
      out.write("        0 0 75px #0072ff,\n");
      out.write("        0 0 100px #0072ff;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #twitter {\n");
      out.write("      animation-delay: 0.3s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #facebook {\n");
      out.write("      animation-delay: 0.5s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #line {\n");
      out.write("      animation-delay: 0.1s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @keyframes AboutAnimate {\n");
      out.write("      from {\n");
      out.write("        filter: hue-rotate(0deg);\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      to {\n");
      out.write("        filter: hue-rotate(360deg);\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("    @media (max-width : 800px) {\n");
      out.write("      #line,\n");
      out.write("      #twitter,\n");
      out.write("      #facebook {\n");
      out.write("        font-size: 3.5em;\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("    @media (max-width : 600px) {\n");
      out.write("      .aboutbag {\n");
      out.write("        display: grid;\n");
      out.write("        grid-template-columns: 10em 1fr;\n");
      out.write("        grid-gap: 1em;\n");
      out.write("        \n");
      out.write("      }\n");
      out.write("\n");
      out.write("      #ABUS {\n");
      out.write("        font-size: 1.5em;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .SocialNetworking {\n");
      out.write("        display: flex;\n");
      out.write("        flex-direction: column;\n");
      out.write("        justify-content: center;\n");
      out.write("        align-items: center;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .SNbag {\n");
      out.write("        margin-top: 1em;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .SNbag:first-child {\n");
      out.write("      margin: 0em;\n");
      out.write("    }\n");
      out.write("      .SNtext {\n");
      out.write("        padding: 0.5em 0;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      #line,\n");
      out.write("      #twitter,\n");
      out.write("      #facebook {\n");
      out.write("        font-size: 2.5em;\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("  <script>\n");
      out.write("\n");
      out.write("  </script>\n");
      out.write("<!-- </body> -->\n");
      out.write("\n");
      out.write("<!-- </html> -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
