/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.9
 * Generated at: 2025-08-05 18:32:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <!-- <meta charset=\"UTF-8\" /> -->\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/fancybox3/jquery.fancybox.css\">\n");
      out.write("  <script src=\"https://kit.fontawesome.com/14c95c3413.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\n");
      out.write("  <script src='");
      out.print(request.getContextPath() );
      out.write("/fancybox3/jquery.fancybox.js'></script>\n");
      out.write("\n");
      out.write("  <title>翁卡克MUISC</title>\n");
      out.write("  <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/images/favicon.ico\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("  ");
 request.getSession(); 
      out.write('\n');
      out.write(' ');
      out.write(' ');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/SubViews/NAV.jsp", out, false);
      out.write("\n");
      out.write("  <div class=\"content\">\n");
      out.write("    ");
 List<String> errors = (List<String>) request.getAttribute("errors");
        
      out.write("\n");
      out.write("        <div class=\"content1\"><!--包裝-->\n");
      out.write("          <div class=\"advertise\">\n");
      out.write("            <img src=\"images/ads/1.png\" id=\"adsimages\">\n");
      out.write("          </div>\n");
      out.write("          <div class=\"loginBag\"><!--包裝-->  \n");
      out.write("            <!--登入資料-->\n");
      out.write("            <form id=\"login\" method=\"POST\" action=\"login.do\">\n");
      out.write("              <img src=\"images/LOGO.png\" class=\"logologin \">\n");
      out.write("              <legend class=\"loginlog\">會員登入</legend>\n");
      out.write("              <div class=\"Package\"><!--包裝-->  \n");
      out.write("                <!--帳號欄位-->\n");
      out.write("                <div class=\"err404\">\n");
      out.write("                  <!--錯誤訊息CSS-->\n");
      out.write("                  ");
      out.print(errors !=null? errors:"");
      out.write("\n");
      out.write("                </div>\n");
      out.write("                <input type=\"text\" name=\"account\" id=\"account\" placeholder=\"帳號或E-MAIL\"\n");
      out.write("                  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty param.account?param.account:cookie.account.value}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                <!--密碼欄位-->\n");
      out.write("                <fieldset class=\"passwordBag\"> <!--包裝-->\n");
      out.write("                  <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"密碼\">\n");
      out.write("                  <i id=\"eyes\" class=\"fas fa-eye\"></i>\n");
      out.write("                  <!-- <i class=\"fas fa-eye-slash\"></i>-->\n");
      out.write("                </fieldset>\n");
      out.write("                <fieldset class=\"keepbag\"><!--包裝-->\n");
      out.write("                  <label>\n");
      out.write("                    <input type=\"checkbox\" id=\"auto\" name=\"auto\" value='ON' ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cookie.auto.value}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\n");
      out.write("                    記住帳號</label>\n");
      out.write("                </fieldset>\n");
      out.write("                <!--驗證碼欄位-->\n");
      out.write("                <fieldset class=\"captchaBag\"><!--包裝-->      \n");
      out.write("                  <input type=\"text\" id=\"captcha\" name=\"captcha\" placeholder=\"驗證碼\" maxlength=\"4\">\n");
      out.write("                  <fieldset class=\"captchapngBag\"><!--包裝-->  \n");
      out.write("                    <img id=\"captchapng\" src=\"images/logincaptcha.png\" alt=\"驗證碼圖\">\n");
      out.write("                    <a href=\"javascript:refreshCaptchapng()\" title=\"刷新驗證碼\">\n");
      out.write("                      <i class=\"fas fa-sync\"></i>\n");
      out.write("                    </a>\n");
      out.write("                  </fieldset>\n");
      out.write("                </fieldset>\n");
      out.write("                <fieldset>\n");
      out.write("                  <input type=\"submit\" id=\"loginBtn\" value=\"登入\">\n");
      out.write("                  <div class=\"Btn\">\n");
      out.write("                    <a href=\"#\" class=\"forgetpwd\">忘記密碼?</a> \n");
      out.write("                    <a href=\"register.jsp\" class=\"register\">註冊</a>\n");
      out.write("                </fieldset>\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("          </form>\n");
      out.write("        </div>\n");
      out.write("  </div>\n");
      out.write("  </div>\n");
      out.write("  <!--登入 END-->\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/SubViews/IntroductionColumn.jsp", out, false);
      out.write("\n");
      out.write("  <!--內容結束-->\n");
      out.write("  <style>\n");
      out.write("    body {\n");
      out.write("      margin: 0;\n");
      out.write("      border: 0;\n");
      out.write("      padding: 0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    fieldset {\n");
      out.write("      margin: 0em;\n");
      out.write("      border: 0;\n");
      out.write("      padding: 0em 0em 0em 0em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .content {\n");
      out.write("      height: 100vh;\n");
      out.write("      display: flex;\n");
      out.write("      flex-direction: row;\n");
      out.write("      justify-content: center;\n");
      out.write("      align-items: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /*錯誤資訊*/\n");
      out.write("    .err404 {\n");
      out.write("      color: #d53030;\n");
      out.write("      font-weight: 600;\n");
      out.write("      font-size: 1.2em;\n");
      out.write("      height: 1.4em;\n");
      out.write("      padding-bottom: 0.1em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /*登入系統*/\n");
      out.write("    .content1 {\n");
      out.write("      border: 0.5em solid gray;\n");
      out.write("      padding: 1em 2em;\n");
      out.write("      height: 29em;\n");
      out.write("      display: flex;\n");
      out.write("      flex-direction: row;\n");
      out.write("      justify-content: center;\n");
      out.write("      align-items: center;\n");
      out.write("      background: no-repeat top/100% url(images/loginbg.jpg);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .advertise {\n");
      out.write("      padding-right: 2em;\n");
      out.write("      width: 30em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .advertise,\n");
      out.write("    .advertise img,\n");
      out.write("    .loginBag,\n");
      out.write("    #login {\n");
      out.write("      height: 26em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .advertise img {\n");
      out.write("      width: 30em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .loginBag {\n");
      out.write("      padding-left: 2em;\n");
      out.write("      border-left: 3px solid rgba(187, 187, 187, 0.959);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #login {\n");
      out.write("      text-align: center;\n");
      out.write("      width: 20em;\n");
      out.write("      background: linear-gradient(45deg, #c0bfbf 30%, #9b9b9b 70%);\n");
      out.write("      border-radius: 10px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .logologin {\n");
      out.write("      margin-top: 0.5em;\n");
      out.write("      width: 5em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .loginlog {\n");
      out.write("      margin: 0em 1.75em;\n");
      out.write("      text-align: center;\n");
      out.write("      font-size: 2em;\n");
      out.write("      color: rgb(247, 255, 251);\n");
      out.write("      border-bottom: 0.125em solid rgba(119, 115, 107, 0.692);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .Package {\n");
      out.write("      display: flex;\n");
      out.write("      flex-direction: column;\n");
      out.write("      align-items: center;\n");
      out.write("      justify-content: space-around;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #account {\n");
      out.write("      margin: 0em 0 0 0;\n");
      out.write("      width: 15em;\n");
      out.write("      height: 2em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .passwordBag {\n");
      out.write("      margin-top: 1em;\n");
      out.write("      position: relative;\n");
      out.write("      width: 100%;\n");
      out.write("      display: flex;\n");
      out.write("      justify-content: center;\n");
      out.write("      align-items: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #password {\n");
      out.write("      margin: 0em 0 0 0;\n");
      out.write("      width: 15em;\n");
      out.write("      height: 2em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .fa-eye,\n");
      out.write("    .fa-eye-slash {\n");
      out.write("      position: absolute;\n");
      out.write("      right: 2em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .keepbag {\n");
      out.write("      display: flex;\n");
      out.write("      justify-content: inherit;\n");
      out.write("      margin: 0.5em 0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .captchaBag {\n");
      out.write("      display: flex;\n");
      out.write("      height: auto;\n");
      out.write("      width: 65%;\n");
      out.write("      justify-content: space-between;\n");
      out.write("      align-items: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #captcha {\n");
      out.write("      margin: 0em 0em 0 0em;\n");
      out.write("      width: 6em;\n");
      out.write("      height: 2em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .captchapngBag {\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #captchapng {\n");
      out.write("      margin: 0 0.5em 0 0;\n");
      out.write("      width: 5em;\n");
      out.write("      height: 1.5em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #loginBtn {\n");
      out.write("      margin: 1.2em 0 0 0;\n");
      out.write("      width: 12.5em;\n");
      out.write("      height: 2em;\n");
      out.write("      font-size: 1em;\n");
      out.write("      background-color: rgb(69, 98, 194);\n");
      out.write("      color: white;\n");
      out.write("      border-radius: 5px;\n");
      out.write("      font-family: 宋體;\n");
      out.write("      text-align: center;\n");
      out.write("      line-height: 0.2em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .Btn {\n");
      out.write("      width: 100%;\n");
      out.write("      margin: 1em 0 0 0;\n");
      out.write("      display: flex;\n");
      out.write("      justify-content: space-between;\n");
      out.write("      align-items: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .forgetpwd,\n");
      out.write("    .register {\n");
      out.write("      text-decoration: none;\n");
      out.write("      color: rgb(4, 106, 202);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .register:hover,\n");
      out.write("    .forgetpwd:hover {\n");
      out.write("      text-decoration: underline;\n");
      out.write("      color: red;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /*小於800PX*/\n");
      out.write("    @media (max-width : 800px) {\n");
      out.write("      .content1 {\n");
      out.write("        border: none;\n");
      out.write("        padding: 0em 0em;\n");
      out.write("        background: none;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .advertise {\n");
      out.write("        display: none;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      .loginBag {\n");
      out.write("        padding-left: 0em;\n");
      out.write("        border-left: none;\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /*登入系統 END*/\n");
      out.write("  </style>\n");
      out.write("  <script>\n");
      out.write("    function refreshCaptchapng() {\n");
      out.write("      //alert(\"refresh captcha\");//測試\n");
      out.write("      captchapng.src = \"images/logincaptcha.png?test=\" + new Date().getTime();\n");
      out.write("    }\n");
      out.write("    /*廣告輪播*/\n");
      out.write("    var photostart = 1;\n");
      out.write("    var photoNum = 10;\n");
      out.write("    $(document).ready(init);\n");
      out.write("    function init() {\n");
      out.write("      setInterval(nextImage, 1500);//輪播秒數\n");
      out.write("    }\n");
      out.write("    function nextImage() {\n");
      out.write("      if (photostart < photoNum) {\n");
      out.write("        photostart++;\n");
      out.write("      } else {\n");
      out.write("        photostart = 1;\n");
      out.write("      }\n");
      out.write("      $(\"#adsimages\").attr(\"src\", \"images/ads/\" + photostart + \".png\");\n");
      out.write("    }\n");
      out.write("\n");
      out.write("  </script>\n");
      out.write("  <!--開關眼-->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/eyes.js\"></script>\n");
      out.write("  <!--開關眼-->\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
