/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.9
 * Generated at: 2025-08-05 18:28:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import uuu.ogkm.entity.Customer;
import java.util.List;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("uuu.ogkm.entity.Customer");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <!-- <meta charset=\"UTF-8\" /> -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/fancybox3/jquery.fancybox.css\">\n");
      out.write("  <script src=\"https://kit.fontawesome.com/14c95c3413.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\n");
      out.write("  <script src='");
      out.print(request.getContextPath() );
      out.write("/fancybox3/jquery.fancybox.js'></script>\n");
      out.write("\n");
      out.write("  <title>翁卡克MUISC</title>\n");
      out.write("  <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/images/favicon.ico\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("  ");
      String _jspx_temp0_url = "/SubViews/NAV.jsp";
      String _jspx_temp0_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp0_url + ((_jspx_temp0_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("會員註冊", _jspx_temp0_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("會員註冊", _jspx_temp0_requestEncoding), out, false);
      out.write("\n");
      out.write("  <div class=\"content\">\n");
      out.write("    ");
 List<String> errors = (List<String>)request.getAttribute("errors");

        String AcctNo = request.getParameter("AcctNo");
        String name = request.getParameter("name");
        String password = request.getParameter("password");
        String email = request.getParameter("email");
        String gender = request.getParameter("gender");
        String birthday = request.getParameter("birthday");
        String captcha = request.getParameter("captcha");
        String oidCaptcha = (String) session.getAttribute("RegisterCaptchaServlet");
        
      out.write("\n");
      out.write("\n");
      out.write("        <!--註冊資料-->\n");
      out.write("        <form id=\"register\" method=\"POST\" action=\"");
      out.print(request.getContextPath());
      out.write("/register.do\">\n");
      out.write("          <div class=\"err404-1\"> <!--包裝-->\n");
      out.write("            <legend><img class=\"registerlogo\" src=\"images/LOGO.png\">會員註冊</legend>\n");
      out.write("            <div class=\"err404-2\"><!--錯誤訊息CSS-->\n");
      out.write("              ");
      out.print(errors !=null && !((AcctNo==null || AcctNo.length()==0) || (name==null || name.length()==0) ||
                (password==null || password.length()==0) || (email==null || email.length()==0) || (gender==null ||
                gender.length()==0) || (birthday==null || birthday.length()==0) || (captcha==null ||
                captcha.length()==0)) ? errors : "" );
      out.write("\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <!--帳號欄位-->\n");
      out.write("          <div class=\"errbag\"> <!--包裝-->\n");
      out.write("            <label for=\"AcctNo\">*帳號:</label>\n");
      out.write("            <div class=\"err404\"><!--錯誤訊息CSS-->\n");
      out.write("              ");
      out.print(errors !=null && (AcctNo==null || AcctNo.length()==0)? errors.get(0):"");
      out.write("\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <input type=\"text\" id=\"AcctNo\" name=\"AcctNo\" placeholder=\"帳號為身分證\">\n");
      out.write("          <!--姓名欄位-->\n");
      out.write("          <div class=\"errbag\"> <!--包裝-->\n");
      out.write("            <label for=\"name\">*姓名:</label>\n");
      out.write("            <div class=\"err404\"> <!--錯誤訊息CSS-->\n");
      out.write("              ");
      out.print(errors !=null && (name==null || name.length()==0)? errors.get(1):"");
      out.write("\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <input type=\"text\" id=\"name\" name=\"name\" placeholder=\"請輸入姓名\">\n");
      out.write("          <!--密碼欄位-->\n");
      out.write("          <div class=\"errbag\"> <!--包裝-->\n");
      out.write("            <label for=\"password\">*密碼:</label>\n");
      out.write("            <div class=\"err404\"> <!--錯誤訊息CSS-->\n");
      out.write("              ");
      out.print(errors !=null && (password==null || password.length()==0)? errors.get(2):"");
      out.write("\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <fieldset id=\"ocpwd\"> <!--包裝-->\n");
      out.write("            <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"長度6-20英、數字\"\n");
      out.write("              minlength=\"");
      out.print( Customer.MIN_PWD_LENGTH );
      out.write("\" maxlength=\"");
      out.print( Customer.MAX_PWD_LENGTH );
      out.write("\">\n");
      out.write("            <i id=\"eyes\" class=\"fas fa-eye\"></i>\n");
      out.write("          </fieldset>\n");
      out.write("          <!--email欄位-->\n");
      out.write("          <div class=\"errbag\"> <!--包裝-->\n");
      out.write("            <label for=\"email\">*e-mail:</label>\n");
      out.write("            <div class=\"err404\"> <!--錯誤訊息CSS-->\n");
      out.write("              ");
      out.print(errors !=null && (email==null || email.length()==0)? errors.get(3):"");
      out.write("\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"example@gmail.com\" list=\"defaultemail\">\n");
      out.write("          <datalist id=\"defaultemail\">\n");
      out.write("            <option value=\"@gmail.com\">\n");
      out.write("            <option value=\"@yahoo.com.tw\">\n");
      out.write("          </datalist>\n");
      out.write("          <!--電話欄位-->\n");
      out.write("          <label for=\"phone\">電話:</label>\n");
      out.write("          <input type=\"tel\" id=\"phone\" name=\"phone\">\n");
      out.write("          <!--地址欄位-->\n");
      out.write("          <label for=\"address1\">地址:</label>\n");
      out.write("          <select name=\"address\" class=\"address\" size=\"0\">\n");
      out.write("            <option value=\"\">--</option>\n");
      out.write("            <option value=\"臺北市\">臺北市</option>\n");
      out.write("            <option value=\"新北市\">新北市</option>\n");
      out.write("            <option value=\"桃園市\">桃園市</option>\n");
      out.write("            <option value=\"臺中市\">臺中市</option>\n");
      out.write("            <option value=\"臺南市\">臺南市</option>\n");
      out.write("            <option value=\"高雄市\">高雄市</option>\n");
      out.write("            <option value=\"基隆市\">基隆市</option>\n");
      out.write("            <option value=\"新竹市\">新竹市</option>\n");
      out.write("            <option value=\"嘉義市\">嘉義市</option>\n");
      out.write("            <option value=\"宜蘭縣\">宜蘭縣</option>\n");
      out.write("            <option value=\"新竹縣\">新竹縣</option>\n");
      out.write("            <option value=\"苗栗縣\">苗栗縣</option>\n");
      out.write("            <option value=\"彰化縣\">彰化縣</option>\n");
      out.write("            <option value=\"南投縣\">南投縣</option>\n");
      out.write("            <option value=\"雲林縣\">雲林縣</option>\n");
      out.write("            <option value=\"嘉義縣\">嘉義縣</option>\n");
      out.write("            <option value=\"屏東縣\">屏東縣</option>\n");
      out.write("            <option value=\"花蓮縣\">花蓮縣</option>\n");
      out.write("            <option value=\"臺東縣\">臺東縣</option>\n");
      out.write("            <option value=\"澎湖縣\">澎湖縣</option>\n");
      out.write("          </select>\n");
      out.write("          <input type=\"text\" id=\"address\" name=\"address1\">\n");
      out.write("          <!--性別欄位-->\n");
      out.write("          <div class=\"errbag\"> <!--包裝-->\n");
      out.write("            <label>*性別:</label>\n");
      out.write("            <div class=\"err404\"><!--錯誤訊息CSS-->\n");
      out.write("              ");
      out.print(errors !=null && (gender==null || gender.length()==0)? errors.get(4):"");
      out.write("\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <select name=\"gender\" id=\"gender\">\n");
      out.write("            <option value='' selected>請選擇</option>\n");
      out.write("            <option value='F'>女</option>\n");
      out.write("            <option value='M'>男</option>\n");
      out.write("            <option value='O'>其他</option>\n");
      out.write("          </select>\n");
      out.write("\n");
      out.write("          <div class=\"register\"> <!--包裝-->\n");
      out.write("            <!--生日欄位-->\n");
      out.write("            <div class=\"errbag\"><!--包裝-->\n");
      out.write("              <label>*生日:</label>\n");
      out.write("              <div class=\"err404\"> <!--錯誤訊息CSS-->\n");
      out.write("                ");
      out.print(errors !=null && (birthday==null || birthday.length()==0)? errors.get(5):"");
      out.write("\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <input type=\"date\" name=\"birthday\" id=\"birthday\">\n");
      out.write("            <!--訂閱欄位-->\n");
      out.write("            <div class=\"sub\">\n");
      out.write("              <label>訂閱:</label>\n");
      out.write("              <input type=\"radio\" id=\"sub1\" name=\"sub\" value=\"true\">\n");
      out.write("              <label for=\"sub1\">是</label>\n");
      out.write("              <input type=\"radio\" id=\"sub2\" name=\"sub\" value=\"false\" checked>\n");
      out.write("              <label for=\"sub2\">否</label>\n");
      out.write("            </div>\n");
      out.write("            <!--驗證碼欄位-->\n");
      out.write("            <div class=\"errbag\"> <!--包裝-->\n");
      out.write("              <input type=\"text\" id=\"captcha\" name=\"captcha\" placeholder=\"驗證碼\" maxlength=\"6\">\n");
      out.write("              <div class=\"err404\"><!--錯誤訊息CSS-->\n");
      out.write("                ");
      out.print(errors !=null && (captcha==null || captcha.length()==0)? errors.get(6):"");
      out.write("\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <fieldset class=\"captcha\"><!--包裝-->\n");
      out.write("              <img id=\"captchapng\" src=\"images/registercaptcha.png\" alt=\"驗證碼圖\">\n");
      out.write("              <a href=\"javascript:refreshCaptchapng()\">\n");
      out.write("                <i class=\"fas fa-sync\"></i>\n");
      out.write("              </a>\n");
      out.write("            </fieldset>\n");
      out.write("            <!--註冊按鈕-->\n");
      out.write("            <input type=\"submit\" id=\"registerBtn\" value=\"註冊\">\n");
      out.write("          </div>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("  <!--註冊 END-->\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/SubViews/IntroductionColumn.jsp", out, false);
      out.write("\n");
      out.write("  <!--內容結束-->\n");
      out.write("  <style>\n");
      out.write("    * {\n");
      out.write("      margin: 0;\n");
      out.write("      padding: 0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /*錯誤資訊*/\n");
      out.write("    .errbag {\n");
      out.write("      display: flex;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .err404-1 {\n");
      out.write("      position: relative;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .err404-2 {\n");
      out.write("      color: #d53030;\n");
      out.write("      font-size: 1.3em;\n");
      out.write("      font-weight: 600;\n");
      out.write("      position: absolute;\n");
      out.write("      right: 0;\n");
      out.write("      top: 110;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .err404 {\n");
      out.write("      color: #d53030;\n");
      out.write("      font-size: 1.3em;\n");
      out.write("      font-weight: 600;\n");
      out.write("      height: 1.4em;\n");
      out.write("      padding-bottom: 0.1em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /*錯誤資訊 END*/\n");
      out.write("    body {\n");
      out.write("      padding: 0;\n");
      out.write("      margin: 0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    legend {\n");
      out.write("      color: rgb(255, 255, 255);\n");
      out.write("      padding-top: 0.5em;\n");
      out.write("      font-size: 1.5em;\n");
      out.write("      border-bottom: 0.2em solid gray;\n");
      out.write("      margin-bottom: 0.2em;\n");
      out.write("      display: flex;\n");
      out.write("      flex-direction: column;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /*註冊系統*/\n");
      out.write("    #register label {\n");
      out.write("      font-size: 1.3em;\n");
      out.write("      width: 4em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #register input[type=\"text\"],\n");
      out.write("    #register input[type=\"email\"],\n");
      out.write("    #register input[type=\"tel\"] {\n");
      out.write("      margin: 0.2em 0;\n");
      out.write("      font-size: 1em;\n");
      out.write("      width: 15em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .content {\n");
      out.write("      padding: 5em 1em;\n");
      out.write("      display: flex;\n");
      out.write("      justify-content: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .registerlogo {\n");
      out.write("      width: 4em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #ocpwd,\n");
      out.write("    .captcha {\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("      border: none;\n");
      out.write("      padding: 0em;\n");
      out.write("      margin: 0em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #password {\n");
      out.write("      margin: 0.2em 0.3em 0 0;\n");
      out.write("      font-size: 1em;\n");
      out.write("      width: 15em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .address {\n");
      out.write("      width: 5em;\n");
      out.write("      font-size: 1em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #gender {\n");
      out.write("      margin: 0.2em 0;\n");
      out.write("      width: 8.3em;\n");
      out.write("      font-size: 1em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #register {\n");
      out.write("      display: flex;\n");
      out.write("      flex-direction: column;\n");
      out.write("      padding: 0 1em;\n");
      out.write("      width: 25em;\n");
      out.write("      background: linear-gradient(45deg, #c0bfbf 30%, #9b9b9b 70%);\n");
      out.write("      border-radius: 0.5em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #birthday {\n");
      out.write("      margin: 0.2em 0;\n");
      out.write("      height: 2em;\n");
      out.write("      width: 10em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .register {\n");
      out.write("      display: flex;\n");
      out.write("      flex-direction: column;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #captcha {\n");
      out.write("      margin: 0em 0 0 0;\n");
      out.write("      width: 10em;\n");
      out.write("      font-size: 1em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #captchapng {\n");
      out.write("      margin: 1em 0.5em 1em 0;\n");
      out.write("      width: 7em;\n");
      out.write("      height: 1.5em;\n");
      out.write("\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .sub {\n");
      out.write("      margin: 0.2em 0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #registerBtn {\n");
      out.write("      width: 10em;\n");
      out.write("      height: 2em;\n");
      out.write("      margin-bottom: 2em;\n");
      out.write("      font-size: 1em;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /*註冊系統 END*/\n");
      out.write("  </style>\n");
      out.write("  <script>\n");
      out.write("    $(document).ready(init);\n");
      out.write("\n");
      out.write("    function init() {\n");
      out.write("      repopulateFrom();\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function repopulateFrom() {\n");
      out.write("		");
if ("POST".equals(request.getMethod())) {
      out.write("\n");
      out.write("        // 		alert(\"POST\");\n");
      out.write("        $(\"intput[name=AcctNo]\").val('");
      out.print(request.getParameter("AcctNo"));
      out.write("');\n");
      out.write("        $(\"intput[name=name]\").val('");
      out.print(request.getParameter("name"));
      out.write("');\n");
      out.write("        $(\"intput[name=password]\").val('");
      out.print(request.getParameter("password"));
      out.write("');\n");
      out.write("        $(\"intput[name=email]\").val('");
      out.print(request.getParameter("email"));
      out.write("');\n");
      out.write("        $(\"intput[name=phone]\").val('");
      out.print(request.getParameter("phone"));
      out.write("');\n");
      out.write("        $(\"select[name=address]\").val('");
      out.print(request.getParameter("address"));
      out.write("');\n");
      out.write("        $(\"intput[name=address1]\").val('");
      out.print(request.getParameter("address1"));
      out.write("');\n");
      out.write("        $(\"select[name=gender]\").val('");
      out.print(request.getParameter("gender"));
      out.write("');\n");
      out.write("        $(\"intput[name=birthday]\").val('");
      out.print(request.getParameter("birthday"));
      out.write("');\n");
      out.write("        $(\".sub[value='");
      out.print(request.getParameter("sub"));
      out.write("']\").prop('checked', true);\n");
      out.write("	");
}
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("    /*驗證碼*/\n");
      out.write("    function refreshCaptchapng() {\n");
      out.write("      //alert(\"refresh captcha\");//測試\n");
      out.write("      captchapng.src = \"images/registercaptcha.png?test=\"\n");
      out.write("        + new Date().getTime();\n");
      out.write("    }\n");
      out.write("		/*驗證碼*/\n");
      out.write("  </script>\n");
      out.write("  <!--開關眼-->\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/eyes.js\"></script>\n");
      out.write("  <!--開關眼-->\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
